### ISSUE TITLE
Improve schema for Autotask cron field

### ISSUE THREAD

**Issue by zeljkoX** [OpenZeppelin/defender-serverless#18]
If possible we should make validation of cron field more stricter.

```
functions:
  autotask-example-1:
    name: 'Hello world from serverless'
    path: './autotasks/hello-world'
    relayer: ${self:resources.Resources.relayers.relayer-1}
    trigger:
      type: "schedule"
      cron: "4"
```

This snippet will pass but it will break UI.

I will create addition issue for API validation.
