### ISSUE TITLE
Relayer network change indicates success, but network does not change

### ISSUE THREAD

**Issue by mok0230** [OpenZeppelin/defender-serverless#34]
Repro:

* Configure a relayer on goerli:

```
goerli-relayer:
        name: "Goerli Relayer"
        network: "goerli"
        min-balance: 1000
```

* Run `sls deploy`
* Change to `network: "mainnet"`
* Run `sls deploy`

Expected:

* Operation fails as changing a Relayer's network is not allowed (I think)

Actual:

* Receive a message indicating success, but Relayer's network remains `goerli`

```
✔ Updated mystack.goerli-relayer (c9b0bc0d-3a47-4547-b399-c79347859ce2)
```
