### ISSUE TITLE
upgrade defender-sentinel-client dependency to ^1.38.0

### ISSUE THREAD

**Issue by peersky** [OpenZeppelin/defender-serverless#42]
In 1.37.0 `NotificationType` did not had `webhook` option. It was [added in 1.38.0](https://github.com/OpenZeppelin/defender-client/commit/870d6c493bde7164cf993b800e788f6f34c9e82b#diff-8803507cc283c298cea4fd3836d779ada71bc7953776b72c6ceb303ea3301802).

Using older versions produces type error when trying to create webhook notification:

```
    notifications:
      testwebhook:
        type: 'webhook'
        name: 'this notification will produce type error'
        config:
          url: '<url>'
        paused: false
```

-> 

```
Running "serverless" from node_modules
========================================================
Secrets
Contracts
Relayers
Autotasks
Notifications
✖ Incompatible notification type webhook
Sentinels
```
