### ISSUE TITLE
Unable to create a datadog notification with serverless deploy

### ISSUE THREAD

**Issue by arbitrary-nomad** [OpenZeppelin/defender-serverless#58]
Relvent config:
```yml
resources:
  Resources:
    notifications:
      datadog-1:
        name: dataddog-main
        type: datadog
        config: 
          api-key: abc123
          metric-p$refix: defenderx.
        paused: false
```

Results in:
```console
╰─$ npx serverless deploy                                                                                               1 ↵
========================================================
Secrets
Contracts
Relayers
Autotasks
Notifications
✖ data/config should have required property 'metricPrefix'
Categories
Sentinels
```

If I change `metric-p$refix` to `metricPrefix`, then it fails validation:
```console
Error:
Configuration error: 
     at 'resources.Resources.notifications.datadog-1.config': unsupported object format
```

I'm using
```
    "defender-serverless": "^1.0.4",
    "serverless": "^3.28.1"
```
