### ISSUE TITLE
Unable to deploy an Autotask with a Sentinel Trigger

### ISSUE THREAD

**Issue by arbitrary-nomad** [OpenZeppelin/defender-serverless#60]
Unable to deploy an Autotask with a Sentinel Trigger

Relevant Code:
```yml
functions:
  autotask-1:
    name: ${self:custom.name} Autotask
    path: autotask-1
    trigger:
      type: sentinel
    paused: false
```

Error recieved:
```console
Error:
Configuration error: 
     at 'functions.autotask-1.trigger.type': must be equal to one of the allowed values [schedule, webhook]
```

Versions:
``` json
    "defender-serverless": "^1.0.5",
    "serverless": "^3.29.0"
```
